---
alias: Day mode air sensors
description: ""
mode: single
triggers:
  - trigger: time
    at: "06:00:00"
conditions: []
actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      label_id:
        - air
